# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67328dfd4e8eafa40aadd176a19e6435ebf43e98d7a184397b20ecfaae4589494b778362686259d61d36274b485c47ea2f95d05d0bc434f2fb9e0387415805b0

test:
  secret_key_base: 1e5a0fec6debc24974ae01c1f8c48aa1938662e7e1323aa47ab8a4f49c25d2c8d05001838faf9deba5578d368aab5928a3ad2caed0f208bf84d42a0256620281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
